# Generated by Django 5.2.1 on 2025-05-15 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('devices', models.IntegerField(default=0)),
                ('farmland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='api.farmland')),
            ],
        ),
    ]
